### ISSUE TITLE
项目运行

### ISSUE THREAD

**Issue by xiaomei1** [uniquejava/node_imooc#1]
是不是只要启动mongodb,再使用node app.js 就可以运行了?

**Comment by uniquejava** [comment]
@xiaomei1 是的, 你要安装mongodb数据库, 并启动起来. mongodb默认会兼听27017端口. 然后运行node app.js

**Comment by imgwho** [comment]
用你的终于跑通了。。给你一个star嘻嘻  加油大兄弟

**Comment by uniquejava** [comment]
@imgwh 随手做的练习, Thanks for your support! 😄
